name: auth

services:
  token:
    build: ./services/token
    env_file: .env
    container_name: auth-token
    restart: unless-stopped
    ports:
      - ${TOKEN_PORT}:${TOKEN_PORT}
    networks:
      server:

networks:
  server:
    driver: bridge
