name: auth

services:
  token:
    build:
      context: .
      dockerfile: services/token/Dockerfile
    env_file: .env
    container_name: auth-token
    restart: unless-stopped
    networks:
      server:

  generator:
    build:
      context: .
      dockerfile: services/generator/Dockerfile
    env_file: .env
    container_name: auth-generator
    restart: unless-stopped
    depends_on:
      server-db:
        condition: service_healthy
    networks:
      server:
    volumes:
      - data:/app/data

  distributor:
    build:
      context: .
      dockerfile: services/distributor/Dockerfile
    env_file: .env
    container_name: auth-distributor
    restart: unless-stopped
    ports:
      - ${DISTRIBUTOR_PORT}:${DISTRIBUTOR_PORT}
    networks:
      server:
    volumes:
      - data:/app/data

  preauth:
    build:
      context: .
      dockerfile: services/preauth/Dockerfile
    env_file: .env
    container_name: auth-preauth
    restart: unless-stopped
    ports:
      - ${PREAUTH_ADD_PORT}:${PREAUTH_ADD_PORT}
      - ${PREAUTH_GET_PORT}:${PREAUTH_GET_PORT}
    networks:
      server:
  
  verifier:
    build:
      context: .
      dockerfile: services/verifier/Dockerfile
    env_file: .env
    container_name: auth-verifier
    restart: unless-stopped
    depends_on:
      client-db:
        condition: service_healthy
    networks:
      client:
      server:

  server-db:
    image: mariadb
    container_name: auth-server-db
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mariadb --user=${SERVER_DB_USER} --password=${SERVER_DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: ${SERVER_DB_NAME}
      MYSQL_USER: ${SERVER_DB_USER}
      MYSQL_PASSWORD: ${SERVER_DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      server:

  client-db:
    image: mariadb
    container_name: auth-client-db
    restart: unless-stopped
    healthcheck:
      test: "/usr/bin/mariadb --user=${CLIENT_DB_USER} --password=${CLIENT_DB_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_DATABASE: ${CLIENT_DB_NAME}
      MYSQL_USER: ${CLIENT_DB_USER}
      MYSQL_PASSWORD: ${CLIENT_DB_PASSWORD}
    volumes:
      - db-client:/var/lib/mysql
    networks:
      client:

  client-db-nosql:
    image: mongo
    container_name: auth-client-db-nosql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      MONGO_INITDB_DATABASE: ${CLIENT_DB_NOSQL_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${CLIENT_DB_NOSQL_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${CLIENT_DB_NOSQL_PASSWORD}
    volumes:
      - db-client-nosql:/data/db
    networks:
      client:
  
  client-db-postgres:
    image: postgres
    container_name: auth-client-db-postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${CLIENT_PGSQL_USER}"]
      interval: 2s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_DB: ${CLIENT_PGSQL_NAME}
      POSTGRES_USER: ${CLIENT_PGSQL_USER}
      POSTGRES_PASSWORD: ${CLIENT_PGSQL_PASSWORD}
    volumes:
      - db-client-postgres:/var/lib/postgresql
    networks:
      client:

  redis:
    image: redis
    container_name: auth-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      server:

volumes:
  db:
  db-client:
  db-client-nosql:
  db-client-postgres:
  redis:
  data:

networks:
  server:
    driver: bridge
  client:
    driver: bridge
