version: "3"

tasks:
  build:
    cmds:
      - docker compose build
  run:
    cmds:
      - docker compose up -d
  modernize:
    cmds:
      - |
        find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
          echo "Running go test in $module_dir"
          (cd "$module_dir" && go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...)
        done
  modernize_fix:
    cmds:
      - |
        find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
          echo "Running go test in $module_dir"
          (cd "$module_dir" && go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -fix -test ./...)
        done
  test:
    cmds:
      - |
        find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
          echo "Running go test in $module_dir"
          (cd "$module_dir" && go test -v ./...)
        done
