# stage 1: building application binary file
FROM golang:1.25 AS builder

RUN mkdir /preauth
ADD services/preauth /preauth
ADD proto /proto
WORKDIR /preauth

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64

RUN go build -o preauth main.go

# stage 2: copy only the application binary file and necessary files to the alpine container
FROM alpine:latest AS production

COPY --from=builder /preauth .

# run the service on container startup
CMD ["./preauth"]
