# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Pull changes from PR branch
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: git pull origin "$PR_HEAD_REF"
      - name: Set up Go
        uses: actions/setup-go@7b8cf10d4e4a01d4992d18a89f4d7dc5a3e6d6f4 # v4
      - name: build
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go build $module_dir"
            (cd "$module_dir" && go build -v ./...)
          done
      - name: test
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go test $module_dir"
            (cd "$module_dir" && go test -v ./...)
          done
      - name: vet
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go vet $module_dir"
            (cd "$module_dir" && go vet ./...)
          done
      - name: modernize
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | grep -v '^./proto$' | while read module_dir; do
            echo "go modernize $module_dir"
            (cd "$module_dir" && go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...)
          done