# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Pull changes from PR branch
        run: git pull origin ${{ github.event.pull_request.head.ref }}
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: build
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go build $module_dir"
            (cd "$module_dir" && go build -v ./...)
          done
      - name: test
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go test $module_dir"
            (cd "$module_dir" && go test -v ./...)
          done
      - name: vet
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go vet $module_dir"
            (cd "$module_dir" && go vet ./...)
          done
      - name: modernize
        run: |
          # Find all go.mod files under the repo
          find . -name 'go.mod' -exec dirname {} \; | while read module_dir; do
            echo "go vet $module_dir"
            (cd "$module_dir" && go run golang.org/x/tools/gopls/internal/analysis/modernize/cmd/modernize@latest -test ./...)
          done