name: Gosec
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GO111MODULE: on
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Pull changes from PR branch
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: git pull origin "$PR_HEAD_REF"
      - name: Install gosec
        run: |
          go install github.com/securego/gosec/v2/cmd/gosec@latest
      - name: Run Gosec Security Scanner
        run: |
          export PATH="$(go env GOPATH)/bin:$PATH"
          find . -name 'go.mod' -exec dirname {} \; | grep -v '^./proto$' | while read module_dir; do
            echo "Running gosec in $module_dir"
            (cd "$module_dir" && gosec -exclude=G402,G404,G117 -exclude-dir=proto ./...)
          done